# This is a basic workflow to help you get started with Actions

name: Run My Test Collection

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'

      - name: Install Newman and allure report
        run: |
          npm install -g newman@latest
          npm install -g newman-reporter-allure
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run Postman Collection #1
        id: run_my_test_collection_1
        run: |
         newman run homework-#1.postman_collection.json -r allure
        continue-on-error: true
      
      - name: Run Postman Collection #2
        id: run_my_test_collection_2
        run: |
         newman run homework-#2.postman_collection.json -e homework-#2.postman_environment.json -r allure
        continue-on-error: true
      
      - name: Run Postman Collection #3
        id: run_my_test_collection_3
        run: |
         newman run homework-#3.postman_collection.json -e homework-#2.postman_environment.json -r allure
        continue-on-error: true
